admins: []
forwards:
- source: -1001558141101
  dest:
  - -1001631273213
  offset: 901
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 5.0
plugins:
  filter:
    text:
      blacklist:
      - badword
    files:
      whitelist:
      - photo
      - video
      - document
